### ISSUE TITLE
Where is nodes.py?

### ISSUE THREAD

**Issue by WillAdams** [Tanneguydv/Pythonocc-nodes-for-Ryven#8]
Is there a step-by-step tutorial which uses a standard file layout?

I can't find "Ryven-master/Ryven/packages/std" on my Ubunty which is what the video shows.

**Comment by leon-thomm** [comment]
yes, this is part of Ryven, for getting started instructions see the [README](https://github.com/leon-thomm/Ryven#quick-start) i.e. quickstart section. the `std` nodes package is in `~/ryven/`

**Comment by WillAdams** [comment]
Thanks! Found it in ~/.local/lib/python3.9/site-packages/ryven/example_nodes/std

**Comment by leon-thomm** [comment]
ah crap, thats true, my bad, the default ones are in `example_nodes` (because they should be considered examples), custom nodes usually go in `~.ryven/`, sorry. you should also see the locations when clicking on the according buttons in the startup dialog

**Comment by WillAdams** [comment]
Thanks. I'm trying to work through other things now. Is there a forum where it would be appropriate to ask questions/get feedback and maybe collaborate on the documentation?

**Comment by leon-thomm** [comment]
there currently is no dedicated place for that. for now, I would suggest GitHub Discussions, it's a good place to share ideas and opinions without filling the issues section with it. you could open a discussion forum here or in the Ryven repo where you post all your questions and suggestions as comments there, as every comment gets its own subthread. or do you have suggestions for creating a new place for this? I'm planning to open a Discord once the Ryven project gets more community...

**Comment by WillAdams** [comment]
Never used Discord, sorry. Not sure how GitHub Discussions works, but I'll check.

Would Reddit be an option? Pretty easy to make a subreddit and /r/Ryven is available.

**Comment by leon-thomm** [comment]
opening a subreddit sounds reasonable too. I just opened r/Ryven to make sure the name doesn't get used for something else, but for technical questions I suggest staying in GitHub for now, because others might look for those primarily here

**Comment by WillAdams** [comment]
Okay, the problem seems to be that I'm not doing everything in the anaconda environment --- I'll have to learn how to use that I guess. Thanks!
